### ISSUE TITLE
Build fails, missing ReaderWriterLock2

### ISSUE THREAD

**Issue by m-mueller678** [wheatman/concurrent-btrees#4]
I tried building the `with_leafds` branch following the Readme on the master branch, however I ran into a couple issues, some of which I was able to fix.

First, I followed these steps:
```
git clone https://github.com/wheatman/concurrent-btrees.git
cd concurrent-btrees
git checckout with_leafds
# Install OpenCilk as instructed here: https://www.opencilk.org/doc/users-guide/install/
git submodule init ./btree_tests/*
git submodule update ./btree_tests/*
export CXX=[path to compiler]
cd btree_tests
rm basic # the repo contains a built version, but I want to build it myself
make CILK=1 DEBUG=0 basic
```
The build fails with `leafDS/leafDS.hpp:4:10: fatal error: 'StructOfArrays/SizedInt.hpp' file not found`.
This can be fixed by running `git submodule update --init --recursive` in the repository root.

However, the build still fails:
 ```
leafDS/leafDS.hpp:78:11: error: expected value in expression
#if AVX512
```

Using `make CILK=1 DEBUG=0 AVX512=0 basic`, I ran into another error:

```
In file included from test.cpp:13:
In file included from ../tlx/container/btree_set.hpp:18:
../tlx/container/btree.hpp:340:17: error: unknown type name 'ReaderWriterLock2'; did you mean 'ReaderWriterLock'?
        mutable ReaderWriterLock2 mutex_;
                ^~~~~~~~~~~~~~~~~
                ReaderWriterLock
```
As I could not find a definition of `ReaderWriterLock2` anywhere in the repo, I am stuck on this.

I am using `opencilk-2.1.0-x86_64-linux-gnu-ubuntu-22.04/bin/clang++`:
```
clang version 16.0.6 (git@github.com:OpenCilk/opencilk-project.git 3f1a18993b8087b1b06c7e891dceec0c86016197)
Target: x86_64-unknown-linux-gnu
Thread model: posix
...
```

**Comment by wheatman** [comment]
Thanks for the report.  We will try and improve the readme and fix it so it just compiles out of the box.

As for `ReaderwriterLock2` the definition is bellow.  Let me know if that works and we will update the repo with it as well.  You can also just change `ReaderWriterLock2` to `ReaderWriterLock`.  They have some different space usage and performance characteristics in the contested and uncontested cases and I would recommend using `ReaderWriterLock2` in most cases.

```
class ReaderWriterLock2 {

public:
  ReaderWriterLock2() : writer(0), readers(0) {}

  /**
   * Try to acquire a lock and spin until the lock is available.
   */
  void read_lock(int cpuid = -1) {

    readers++;

    while (writer.test(std::memory_order_relaxed)) {
      readers--;
      writer.wait(true, std::memory_order_relaxed);
      readers++;
    }
  }

  void read_unlock(int cpuid) {
    readers--;
    return;
  }

  /**
   * Try to acquire a write lock and spin until the lock is available.
   * Then wait till reader count is 0.
   */
  void write_lock() {
    // acquire write lock.
    while (writer.test_and_set(std::memory_order_acq_rel)) {
      writer.wait(true, std::memory_order_acq_rel);
    }
    // wait for readers to finish
    while (readers > 0) {
    }
  }

  void write_unlock(void) {
    writer.clear(std::memory_order_release);
    writer.notify_all();
    return;
  }

private:
  std::atomic_flag writer{false};
  std::atomic<int> readers{};
};

```

**Comment by m-mueller678** [comment]
After adding the definition to `btree.hpp`, I get this (inside function `exists`):
```
../tlx/container/btree.hpp:1748:38: error: too few arguments to function call, single argument 'cpuid' was not specified
            leaf->mutex_.read_unlock();
```
replacing it with `ReaderWriterLock` yields the same error

**Comment by wheatman** [comment]
my mistake 
```class ReaderWriterLock2 {

public:
  ReaderWriterLock2() : writer(0), readers(0) {}

  /**
   * Try to acquire a lock and spin until the lock is available.
   */
  void read_lock(int cpuid = -1) {

    readers++;

    while (writer.test(std::memory_order_relaxed)) {
      readers--;
      writer.wait(true, std::memory_order_relaxed);
      readers++;
    }
  }

  void read_unlock(int cpuid = -1) {
    readers--;
    return;
  }

  /**
   * Try to acquire a write lock and spin until the lock is available.
   * Then wait till reader count is 0.
   */
  void write_lock() {
    // acquire write lock.
    while (writer.test_and_set(std::memory_order_acq_rel)) {
      writer.wait(true, std::memory_order_acq_rel);
    }
    // wait for readers to finish
    while (readers > 0) {
    }
  }

  void write_unlock(void) {
    writer.clear(std::memory_order_release);
    writer.notify_all();
    return;
  }

private:
  std::atomic_flag writer{false};
  std::atomic<int> readers{};
};

**Comment by itshelenxu** [comment]
Please check the new main branch, which I cleaned up to remove the dependency on cilk and to make running the experiments smoother. ParallelTools has been updated with ReaderWriterLock2. Here is more documentation: 
https://docs.google.com/document/d/1GqQBpYTzSixPAQMfuK8pHyDVL7OjqDHb-Q0u406x894/edit#heading=h.dcbs04rhzkfs

Let us know if there are any questions / issues. Thank you!

**Comment by m-mueller678** [comment]
- The ordering of cd and git checkout in the doc is flipped
- the doc refers to `btree_tests/ParallelTools/ParallelTools/Lock.cpp`, which does not exist (it is header only).
- ReaderWriterLock2 is not in the Lock header

manually adding [ReaderWriterLock2](https://github.com/wheatman/concurrent-btrees/issues/4#issuecomment-2079292637)  it compiles and seems to work. Thank you for your help.

**Comment by itshelenxu** [comment]
Thank you for the notes - I have updated the doc to fix the first two issues.

We have updated the ParallelTools repo to include ReaderWriterLock2: https://github.com/wheatman/ParallelTools/blob/main/ParallelTools/Lock.hpp

Please update the submodule to get it.
